script:
- git config user.name "jdmedlock"
- git config user.email "jdmedlock@gmail.com"
- git remote remove origin
- git remote add origin https://927bd232b30bfa0c9ba68ce93cd3eef8a9368c8d@github.com/jdmedlock/wikiprtest-collab.git
  > /dev/null 2>&1
- git remote add upstream https://927bd232b30bfa0c9ba68ce93cd3eef8a9368c8d@github.com/jdmedlock/wikiprtest-wiki.wiki.git
  > /dev/null 2>&1
- git fetch origin
- git fetch upstream
- git merge upstream/master --no-edit
- git push origin HEAD:master > /dev/null 2>&1
- git push upstream HEAD:master > /dev/null 2>&1
env:
  matrix:
  - secure: E+S3Q6aS8Y0sl87jRaGYK9iZqQRhmD3igdfbXUqX0kARSnG6JC55V3qFD0pVgxS6st/r7iLNbT6WosVkny88fADQXJobLyj+dk6/4h4Ut6UydINttLAjnmAUAHPgbVVA0cjQR2y2iaqdeS1ykUYuMUFXRIpRIaZavV1VFR31uAlLY6u395NWMSH6iJVuda6N8itPOfJaWB8WGATLikRyd+1qSFYyUW+0SI4/pa8HaPDJboHMtqxIPU1rPNnWeN2LpHYOhg0neA0mI0kWusoHcCh1y1zLrEDw4wWG2nn1HPGMhQWjXNjhgyH2gOavUQe7LryhD1rRwSn+7riSIKYH4dhX4Swua4YjxLzn8BwzBGd7vad4CtrK+tNCLgb4BtfBsgQ8FXmj8tZLVF75o7Q2X390Q0LlOwwcK3iqX75XO5MkVNgCHalny9e/DO9fnw6Y8M/Iis5TPOdjJlffrEfwqceUQKYVaotpRFO9cOkErTmJT6Tepc4e4IW9s7MEkJ3qvhAJyS+9P4QuFvgRd9MDESM8dolyln0B4xYJPEP9mnPWJeSQzefTvJZNJ8n0GATjNCOzV2iZv7ZZa3x0sR2w3NksZ/pK1terZ1JXeSmUXWq1ADM8VJT+RyGpgtAQ/zp57m1eEqO/JZwTuV0N9PH9yZn3ktcIA/5IVS9M4ep9Op4=
