script:
- git config user.name "jdmedlock"
- git config user.email "jdmedlock@gmail.com"
- git remote remove origin
- git remote add origin https://$GITHUB_API_KEY@github.com/jdmedlock/wikiprtest-collab.git
  > /dev/null 2>&1
- git remote add upstream https://$GITHUB_API_KEY@github.com/jdmedlock/wikiprtest-wiki.wiki.git
  > /dev/null 2>&1
- git fetch origin development
- git fetch upstream
- git merge upstream/master --no-edit
- git push origin HEAD:master > /dev/null 2>&1
- git push upstream HEAD:master > /dev/null 2>&1
env:
  matrix:
    secure: JHC8dLafYgrpVsDomi66t+rNMSdgHwXaou9B+hzMaRkqv+Y2oBt3v0qAq3pFHpksuS0ReUhYFPXV0vAaPIgI6tp5P7g8jc4kT1UsMy0EwiCoJ1RC3eRzTrKzH/W7+pID+YsVVGxkpfTGliJNmTaDLj4nRLvnEBgiy30s5Nk4RsxNr7DaXDu/PTSnH5W7odAsW5DcorV/SyvOz3N2HQ1Gtr6udgfvVmPmfvDVpB4oQ0VSvcn/2CEGhT2rKfLtqqPNeHxrzq+tMqqddK6vcS0mQRhQo9GtxCO4iCOCW7LbrA5VAYKTBxw+fEcCHkhl16zr88XLzxyQ8vvDutszMlxSlaRMO3gxEqsCMf8E40myBJJEGkkGe27qstf9tvz83ZiIJR04s0ImvI3l5xFnIy5lvVRUmXcR3P7djn2raTN0W4EWOMrvqAmaAVtHJMpTln5ClwcnkrQ1+6tbFVSLmwtj1EJD5L8ZszRO5DmtDPEG96e7VtcAWuJN/HlFXjF62MIHB11drxNXl1wnoG3JMqphqx7eMeil8YdOlnWUeq177e9bjD3AUbWRbS9MjKsphGLQfcOiwd04/N54Uesa7Hrz52HQeCOlliGyn1vC7sZexVLedUMFj0ISsyElz/UtcPBu+Fi8fj7Rq2vUPJ7Qicwr/B572oTniY/QvMjirKuCU7I=
